name: Distribute

on:
  push:
    paths-ignore:
    - 'README.md'
    - '.github/workflows/gradle.yml'
    - '.github/workflows/app_distribute.yml'
    branches: [ qa ]

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore_prod.jks.b64
          base64 -d -i keystore_prod.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties

        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Decode data google-services.json for Debug
        env:
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}
        run: echo $GOOGLE_SERVICES_DEBUG > data/src/debug/google-services.json

      - name: Decode data google-services.json for Release
        env:
          GOOGLE_SERVICES_RELEASE: ${{ secrets.GOOGLE_SERVICES_RELEASE }}
        run: echo $GOOGLE_SERVICES_RELEASE > data/src/release/google-services.json

      - name: ktlint
        run: ./gradlew ktlintCheck

      - name: Unit Tests
        run: ./gradlew test

      - name: Create Firebase Service Credentials file
        run: |
          echo "$FIREBASE_APP_DISTRIBUTION_CREDENTIALS" > firebase_app_distribution_credentials.json.b64
          base64 -d -i firebase_app_distribution_credentials.json.b64 > firebase_app_distribution_credentials.json
        env:
          FIREBASE_APP_DISTRIBUTION_CREDENTIALS: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}

      - name: Decode app google-services.json for Debug
        env:
          GOOGLE_SERVICES_APP_DEBUG: ${{ secrets.GOOGLE_SERVICES_APP_DEBUG }}
        run: |
          mkdir app/src/debug/
          echo $GOOGLE_SERVICES_APP_DEBUG > app/src/debug/google-services.json

      - name: Decode app google-services.json for Release
        env:
          GOOGLE_SERVICES_APP_RELEASE: ${{ secrets.GOOGLE_SERVICES_APP_RELEASE }}
        run: |
          mkdir app/src/debug/
          echo $GOOGLE_SERVICES_APP_RELEASE > app/src/release/google-services.json

      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane distribute
        env:
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
