# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/workflows/gradle.yml'
      - '.github/workflows/app_distribute.yml'
    branches: [ dev, master, release/*, hotfix/* ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore_prod.jks.b64
          base64 -d -i keystore_prod.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties

        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Decode google-services.json for Debug
        env:
          GOOGLE_SERVICES_DEBUG: ${{ secrets.GOOGLE_SERVICES_DEBUG }}
        run: |
          mkdir app/src/debug/
          echo $GOOGLE_SERVICES_DEBUG > app/src/debug/google-services.json
          cat app/src/debug/google-services.json

      - name: Decode google-services.json for Release
        env:
          GOOGLE_SERVICES_RELEASE: ${{ secrets.GOOGLE_SERVICES_RELEASE }}
        run: echo $GOOGLE_SERVICES_RELEASE > app/src/release/google-services.json

      - name: ktlint
        run: ./gradlew ktlintCheck

      - name: Unit Tests
        run: ./gradlew test

      - name: Upload test report (failure only)
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '*/build/reports/tests'

      - name: Upload Jacoco test coverage report (success only)
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-test-reports
          path: '*/build/reports/jacocoTestReport'
